name: teste_cypress_pdf

on:
  workflow_dispatch

jobs:
  teste:
    runs-on: windows-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Docker login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_HUB_USER}}
          password: ${{ secrets.DOCKER_HUB_TOKEN}}
