name: teste_cypress_pdf

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email usado para receber o pdf da API'
        required: true
        default: pdf_testmail@yopmail.com
        type: string
      pdf_name:
        description: 'Nome do arquivo PDF gerado'
        required: true
        default: test_pdf
        type: string

jobs:
  teste:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Docker login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Run Docker Container
        run: |
          docker compose up -d

      - name: Install Cypress Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: |
          echo "Running Cypress tests on docker container"
          npx cypress run --env url=http://localhost:5000/pdf,file_name=${{ inputs.pdf_name,email=${{ inputs.email --reporter mochawesome

      - name: uploading artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Index
          path: mochawesome-report
          retention-days: 30

      - name: Stop and cleanup
        run: |
          docker compose down --rmi all || true
